baseURL = ""
languageCode = "en-IN"
title = "Poonam Shelke's blog"
theme = "github-style"

[params]
author = "Poonam"
description = "developer"
github = "punam-shelke"
linkedin = "punam-shelke-636626140"
location = "India"
userStatusEmoji = "❤️"
avatar = "/images/profile.jpg"
url = "https://meik2333.com"        #TODO: change the url

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
